experiment:
  seed: 42
  n_trials: 100
  horizon: 30000
task: averaging
path:
  folder: exp14
  output: results.pkl
data:
  type: real
  n: 100
  treshold: 0
  eps: 0.1
  outlier: 100
graph: 2D Grid
ranking: All
trimming:
  alpha: 0.2
clipping:
  tau: 50
