experiment:
  seed: 42
  n_trials: 100
  horizon: 150000
task: averaging
path:
  folder: exp28b
  output: results.pkl
data:
  type: arange
  n: 5000
  treshold: 0
  eps: 0.1
  outlier: 100
graph: 2D Grid
ranking: All
trimming:
  alpha: 0.2
clipping:
  tau: 50
