experiment:
  seed: 42
  n_trials: 10
  horizon: 150000
task: averaging
path:
  folder: exp36
  output: results.pkl
data:
  type: arange
  n: 500
  eps: 0.1
  outlier: 10
graph: Cycle
ranking: GoRank
trimming:
  alpha: 0.2
clipping:
  tau: 50
